Fix stage duration on stage overview
gocd/gocd pull request #8690
Opened 2020-10-27 09:03 UTC by maheshp

Issue: #8681 

Description: Fix stage duration on stage overview. It is same as the Stage details page.

Introduced v3 of Stage Instance API.

2020-10-27 13:00 UTC, kritika-singh3 requested changes
LGTM.
Should we add the new attributes to the history API as well??

2020-10-28 03:39 UTC, maheshp commented on api/api-stage-instance-v3/src/main/java/com/thoughtworks/go/apiv3/stageinstance/representers/StageRepresenter.java
> +        jsonWriter.add("created_time", stage.getCreatedTime().getTime());
Changed it to `scheduled_at`.

2020-10-28 03:48 UTC, maheshp commented
> Should we add the new attributes to the history API as well??

I did look at the history API, since the Stage JSON had minimal attributes compared to the Stage instance API I thought we can add it later if required.

2020-10-28 04:20 UTC, kritika-singh3 approved these changes

2020-10-28 04:41 UTC, merged

2020-10-29 08:28 UTC, kritika-singh3 commented
Verified on `GoCD Version: 20.9.0 (12318-b67833a26e7273f83019facdf22dfcfd290cdf4a)`